# general configuration
url: http://lucypatterson.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/lucy.png"
  # author will appear under the avatar (optional)
  author: "Lucy Patterson"
  # tagline will appear under the title (optional)
  tagline: "Escaped scientist with Stockholm Syndrome #openscience #diyscience #sciart #berlin"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments

# Permalinks
permalink: pretty
